<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Kripalu-Kunj" failures="1" tests="3" name="Test3" time="10.056" errors="0" timestamp="2025-01-19T22:41:25 IST">
  <testcase classname="com.soni.JKP1008.TestClass_3" name="test1" time="0.018">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.soni.JKP1008.TestClass_3.test1(TestClass_3.java:14)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="com.soni.JKP1008.TestClass_3" name="test2" time="10.027"/>
  <testcase classname="com.soni.JKP1008.TestClass_3" name="test3" time="10.027"/>
</testsuite> <!-- Test3 -->
